import fs from 'node:fs/promises';
import path from 'node:path';
import { spawn, spawnSync } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import { pathToFileURL, fileURLToPath } from 'node:url';
import net from 'node:net';

// No external URL is accepted: all writes target a fresh local D1 directory.
const args = Object.fromEntries(process.argv.slice(2).map(x => { const i=x.indexOf('='); return [x.slice(0,i),x.slice(i+1)]; }));
const repo = path.resolve(args['--repo'] || process.cwd());
const root = path.dirname(fileURLToPath(import.meta.url));
const out = path.resolve(args['--out'] || path.join(repo, '.argo/runtime/screenshots', new Date().toISOString().replaceAll(':','-')));
const port = Number(args['--port'] || 8797);
if (!Number.isInteger(port) || port < 1024 || port > 65535) throw Error('Invalid local port');
await fs.mkdir(out, {recursive:true});
const local = path.join(out,'isolated-'+randomUUID());
await fs.mkdir(local);
const configPath=path.join(local,'wrangler.json');
const dist=path.join(local,'dist');
await fs.cp(path.join(repo,'dist'),dist,{recursive:true});
const source=JSON.parse(await fs.readFile(path.join(dist,'server','wrangler.json'),'utf8'));
const config={name:'puzzle-regression-local',main:'./dist/server/'+source.main,compatibility_date:source.compatibility_date,compatibility_flags:source.compatibility_flags,no_bundle:true,rules:source.rules,assets:{directory:'./dist/client'},d1_databases:[{binding:'DB',database_name:'regression-local',database_id:'00000000-0000-4000-8000-000000000000'}],vars:{INITIAL_ADMIN_PASSWORD:'Regression-Local-Only-2026'}};
await fs.writeFile(configPath,JSON.stringify(config,null,2));
const cli=path.join(repo,'node_modules','wrangler','bin','wrangler.js');
const state=path.join(local,'state');
const env={...process.env,WRANGLER_SEND_METRICS:'false',WRANGLER_LOG_PATH:path.join(local,'wrangler-logs')};
const report={schema:1,runAt:new Date().toISOString(),origin:`http://127.0.0.1:${port}`,scope:'existing dist; fresh isolated local D1; no deploy',checks:[],screenshots:[],browserErrors:[],networkErrors:[],navigationCancellations:[],comparison:null};
const check=(name,ok,detail='')=>{report.checks.push({name,ok,detail});if(!ok)throw Error(name+': '+detail);};
const wrangler=(extra)=>{const r=spawnSync(process.execPath,[cli,...extra,'--config',configPath],{cwd:local,env,encoding:'utf8',windowsHide:true});if(r.status!==0)throw Error('Local wrangler operation failed: '+r.stderr.slice(-1500));};
let server,browser;
try {
  await new Promise((resolve,reject)=>{const probe=net.createServer();probe.once('error',()=>reject(Error('Refusing occupied local port')));probe.listen(port,'127.0.0.1',()=>probe.close(resolve));});
  const sql=(await fs.readdir(path.join(repo,'drizzle'))).filter(x=>x.endsWith('.sql')).sort();
  for(const file of sql) wrangler(['d1','execute','DB','--local','--persist-to',state,'--file',path.join(repo,'drizzle',file)]);
  report.migrations=sql;
  const log=await fs.open(path.join(local,'server.log'),'w');
  server=spawn(process.execPath,[cli,'dev','--config',configPath,'--local','--persist-to',state,'--ip','127.0.0.1','--port',String(port),'--inspector-port','0'],{cwd:local,env,windowsHide:true,stdio:['ignore',log.fd,log.fd]});
  const base=report.origin;
  for(let i=0;i<90;i++){if(server.exitCode!==null)throw Error('Local server exited during startup');try{if((await fetch(base)).status===200)break;}catch{}if(i===89)throw Error('Local server startup timeout');await new Promise(r=>setTimeout(r,500));}
  const pw=args['--playwright'] || process.env.REGRESSION_PLAYWRIGHT || path.join(process.env.USERPROFILE || process.env.HOME || '', '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
  const {chromium}=await import(pathToFileURL(pw));
  browser=await chromium.launch({headless:true,...(args['--browser'] || process.env.REGRESSION_BROWSER ? {executablePath:args['--browser'] || process.env.REGRESSION_BROWSER} : process.platform==='win32' ? {channel:'chrome'} : {})});
  report.browserVersion=browser.version();
  async function context(){const c=await browser.newContext({locale:'zh-TW',timezoneId:'Asia/Taipei',colorScheme:'light',reducedMotion:'reduce',viewport:{width:1440,height:1000}});await c.addInitScript(() => {const NativeDate=Date;class FixedDate extends NativeDate {constructor(...args){super(...(args.length?args:['2026-09-23T12:00:00.000Z']));}static now(){return NativeDate.parse('2026-09-23T12:00:00.000Z');}}window.Date=FixedDate;});return c;}
  const admin=await context(),member=await context(),coordinator=await context(),anon=await context();
  const authTransitions=new WeakMap();
  const api=async(c,url,method='GET',data)=>c.request.fetch(base+url,{method,data,headers:{Origin:base}});
  const status=async(name,c,url,expected,method,data)=>{const r=await api(c,url,method,data);check(name,r.status()===expected,`HTTP ${r.status()}, expected ${expected}`);return r;};
  await status('Anonymous workspace denied',anon,'/api/workspace',401);
  await status('Anonymous member list denied',anon,'/api/members',403);
  const page=await admin.newPage();
  function observe(p,role){p.on('pageerror',e=>report.browserErrors.push({role,type:'pageerror',message:e.message}));p.on('console',m=>{if(m.type()==='error')report.browserErrors.push({role,type:'console',message:m.text()});});p.on('requestfailed',r=>{const item={role,url:new URL(r.url()).pathname,error:r.failure()?.errorText,resourceType:r.resourceType(),isNavigation:r.isNavigationRequest(),rsc:r.headers()['rsc']||null,authTransition:authTransitions.get(p)||null};if(authTransitions.has(p)&&(r.isNavigationRequest()||r.headers()['rsc']==='1')&&new URL(r.url()).origin===base&&item.url==='/'&&item.error==='net::ERR_ABORTED')report.navigationCancellations.push(item);else report.networkErrors.push(item);});p.on('response',r=>{if(r.status()>=400)report.networkErrors.push({role,url:new URL(r.url()).pathname,status:r.status()});});}
  observe(page,'admin');
  async function shot(p,name){await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:path.join(out,name+'.png'),fullPage:true,animations:'disabled'});const bytes=await fs.readFile(path.join(out,name+'.png'));const structure=await p.locator('body').innerText();report.screenshots.push({name,sha256:createHash('sha256').update(bytes).digest('hex'),text:structure});}
  async function login(p,username){await p.goto(base);authTransitions.set(p,'login');await p.locator('#login-username').fill(username);await p.locator('#login-password').fill('Regression-Local-Only-2026');await p.locator('form').getByRole('button',{name:'登入',exact:true}).click();await p.getByRole('heading',{name:'營運總覽',exact:true}).waitFor();await p.locator('.sync').filter({hasText:'已同步'}).waitFor();authTransitions.delete(p);}
  await page.goto(base);await shot(page,'login-desktop');
  await page.setViewportSize({width:390,height:844});await shot(page,'login-mobile');await page.setViewportSize({width:1440,height:1000});
  const pattern=await page.locator('#login-username').getAttribute('pattern');
  const patternValid=await page.evaluate(p=>{try{new RegExp(p,'v');return true;}catch{return false;}},pattern);
  report.checks.push({name:'Login HTML pattern compiles with v flag',ok:patternValid,detail:patternValid?'':'Invalid HTML pattern'});
  await status('Wrong password rejected',anon,'/api/auth/login',401,'POST',{username:'invalid.user',password:'Wrong-Password-2026'});
  await login(page,'kao19950411');check('Admin UI login',true);
  await status('Admin member list allowed',admin,'/api/members',200);
  const createdMember=await status('Create isolated member',admin,'/api/members',201,'POST',{username:'regression.member',displayName:'Regression Member',role:'member',password:'Regression-Local-Only-2026'});
  const memberId=(await createdMember.json()).member?.id;
  const createdCoordinator=await status('Create isolated coordinator',admin,'/api/members',201,'POST',{username:'regression.coordinator',displayName:'Regression Coordinator',role:'coordinator',password:'Regression-Local-Only-2026'});
  await status('Coordinator API login',coordinator,'/api/auth/login',200,'POST',{username:'regression.coordinator',password:'Regression-Local-Only-2026'});
  await status('Coordinator registration private API allowed',coordinator,'/api/registration-forms?activityId=regression-activity',200);
  await status('Coordinator member management allowed',coordinator,'/api/members',200);
  await page.getByRole('navigation',{name:'主要導覽',exact:true}).getByRole('button',{name:'成員管理',exact:true}).click();
  await page.getByRole('button',{name:'＋ 新增成員'}).click();
  const createDialog=page.getByRole('dialog',{name:'新增成員'});
  await createDialog.locator('input[name="username"]').fill('regression.manager');
  await createDialog.locator('input[name="name"]').fill('Regression Manager');
  await createDialog.locator('input[name="password"]').fill('Regression-Local-Only-2026');
  check('Admin UI exposes general manager',await createDialog.locator('select[name="role"] option[value="manager"]').count()===1);
  await createDialog.locator('select[name="role"]').selectOption('manager');
  await createDialog.getByRole('button',{name:'新增成員',exact:true}).click();
  await createDialog.waitFor({state:'hidden'});
  const createdManagerList=await (await api(admin,'/api/members')).json();
  const managerId=createdManagerList.members.find(row=>row.username==='regression.manager')?.id;
  check('Admin UI creates general manager in isolated DB',Boolean(managerId&&createdManagerList.members.some(row=>row.id===managerId&&row.role==='manager'&&row.status==='active')));
  const manager=await context();
  await status('Manager API login',manager,'/api/auth/login',200,'POST',{username:'regression.manager',password:'Regression-Local-Only-2026'});
  const coordinatorId=(await createdCoordinator.json()).member?.id;
  check('Role ids available',Boolean(managerId&&coordinatorId));
  await status('Coordinator cannot change manager',coordinator,'/api/members',403,'PATCH',{id:managerId,status:'disabled'});
  await status('Manager cannot promote coordinator to peer',manager,'/api/members',403,'PATCH',{id:coordinatorId,role:'manager'});
  const pendingCoordinator=await status('Manager adds pending coordinator',manager,'/api/members',201,'POST',{username:'regression.newcoordinator',displayName:'Regression New Coordinator',role:'coordinator',status:'pending',password:'Regression-Local-Only-2026'});
  const pendingCoordinatorId=(await pendingCoordinator.json()).member?.id;
  await status('Manager approves coordinator',manager,'/api/members',200,'PATCH',{id:pendingCoordinatorId,status:'active'});
  await status('Manager cannot add peer manager',manager,'/api/members',403,'POST',{username:'regression.peermanager',displayName:'Peer Manager',role:'manager',password:'Regression-Local-Only-2026'});
  const pendingLeader=await status('Coordinator adds pending leader',coordinator,'/api/members',201,'POST',{username:'regression.leader',displayName:'Regression Leader',role:'leader',status:'pending',password:'Regression-Local-Only-2026'});
  const leaderId=(await pendingLeader.json()).member?.id;
  await status('Coordinator approves leader',coordinator,'/api/members',200,'PATCH',{id:leaderId,status:'active'});
  const pendingMember=await status('Coordinator adds pending member',coordinator,'/api/members',201,'POST',{username:'regression.secondmember',displayName:'Regression Second Member',role:'member',status:'pending',password:'Regression-Local-Only-2026'});
  await status('Coordinator approves member',coordinator,'/api/members',200,'PATCH',{id:(await pendingMember.json()).member?.id,status:'active'});
  await status('Coordinator cannot add peer',coordinator,'/api/members',403,'POST',{username:'regression.peercoordinator',displayName:'Peer Coordinator',role:'coordinator',password:'Regression-Local-Only-2026'});
  const leader=await context();
  await status('Leader API login',leader,'/api/auth/login',200,'POST',{username:'regression.leader',password:'Regression-Local-Only-2026'});
  await status('Leader member list denied',leader,'/api/members',403);
  await status('Leader cannot approve member',leader,'/api/members',403,'PATCH',{id:memberId,status:'active'});
  report.checks.push({name:'No browser console or runtime errors',ok:report.browserErrors.length===0,detail:`${report.browserErrors.length} errors`});
  check('No failed browser network responses',report.networkErrors.length===0,`${report.networkErrors.length} errors`);
}catch(e){report.failure=e.message;process.exitCode=1;}finally{if(browser)await browser.close();if(server){if(process.platform==='win32')spawnSync('taskkill',['/pid',String(server.pid),'/t','/f'],{windowsHide:true,stdio:'ignore'});else server.kill();}report.passed=!report.failure && report.checks.every(x=>x.ok);if(!report.passed)process.exitCode=1;await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,out,failure:report.failure}));}
